name: Update Samples

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  main:
    name: Update Samples
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Update Samples
        run: ./scripts/UpdateSamples.ps1
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-samples
          delete-branch: true
          title: |
            Update Quickstart & AVM Sample Links
          draft: false