name: Update Samples

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  update-samples:
    name: Update Samples
    permissions:
      contents: write
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4

      - name: Clone quickstarts
        uses: actions/checkout@v4
        with:
          repository: Azure/azure-quickstart-templates
          path: workflow-temp/azure-quickstart-templates

      - name: Update Samples
        shell: pwsh
        run: ./scripts/UpdateSamples.ps1 -QuickStartsRepoPath workflow-temp/azure-quickstart-templates

      - name: Update Baselines
        run: ./scripts/update_baselines.sh
        # this will fail if there are changes - this is expected
        continue-on-error: true

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Quickstart & AVM samples
          file_pattern: settings/samples src/TemplateRefGenerator.Tests/Files
          branch: update-samples
          push_options: '--force'
          create_branch: true